package observability

import (
	"fmt"
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	// MessagesProduced tracks the total number of messages produced
	MessagesProduced = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "edalab_messages_produced_total",
			Help: "Total number of messages produced",
		},
		[]string{"service", "topic"},
	)

	// MessagesConsumed tracks the total number of messages consumed
	MessagesConsumed = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "edalab_messages_consumed_total",
			Help: "Total number of messages consumed",
		},
		[]string{"service", "topic"},
	)

	// MessageLatency tracks message processing latency
	MessageLatency = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "edalab_message_latency_seconds",
			Help:    "Message processing latency in seconds",
			Buckets: prometheus.ExponentialBuckets(0.001, 2, 15), // 1ms to ~16s
		},
		[]string{"service", "topic"},
	)

	// ProcessingErrors tracks processing errors
	ProcessingErrors = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "edalab_processing_errors_total",
			Help: "Total number of processing errors",
		},
		[]string{"service", "error_type"},
	)

	// ActiveConnections tracks active WebSocket connections
	ActiveConnections = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "edalab_active_connections",
			Help: "Number of active connections",
		},
		[]string{"service", "type"},
	)

	// SimulationStatus tracks simulation state
	SimulationStatus = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "edalab_simulation_status",
			Help: "Current simulation status (1=running, 0=stopped)",
		},
		[]string{"service"},
	)

	// EventsGenerated tracks events generated by simulator
	EventsGenerated = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "edalab_events_generated_total",
			Help: "Total number of events generated by simulator",
		},
		[]string{"event_type"},
	)

	// DatabaseOperations tracks database operations
	DatabaseOperations = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "edalab_database_operation_seconds",
			Help:    "Database operation duration in seconds",
			Buckets: prometheus.ExponentialBuckets(0.0001, 2, 15),
		},
		[]string{"service", "operation"},
	)
)

// RegisterMetrics registers all metrics with the default registry
func RegisterMetrics() {
	prometheus.MustRegister(
		MessagesProduced,
		MessagesConsumed,
		MessageLatency,
		ProcessingErrors,
		ActiveConnections,
		SimulationStatus,
		EventsGenerated,
		DatabaseOperations,
	)
}

// NewMetricsServer creates a new HTTP server for exposing metrics
func NewMetricsServer(port int) *http.Server {
	mux := http.NewServeMux()
	mux.Handle("/metrics", promhttp.Handler())
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("OK"))
	})

	return &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: mux,
	}
}
